/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.amalia;

import com.amalia.utillity.FirebaseUtil;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage primaryStage) throws Exception {
        FirebaseUtil.initializeFirebase(); // Initialize Firebase connection
        Parent root = FXMLLoader.load(getClass().getResource("/com/amalia/view/login.fxml"));
        primaryStage.setTitle("Note Taking App");
        primaryStage.setScene(new Scene(root, 800, 600));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

}
